# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
